services:
  db:
    image: mysql:5.7
    container_name: mysql_db_new
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newwebdb
    ports:
      - "3301:3306"  
    volumes:
      - mysql_data_new:/var/lib/mysql
    networks:
      - weblab820
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_new
    environment:
      PMA_HOST: mysql_db_new
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "3302:80"
    depends_on:
      - db
    networks:
      - weblab820
    restart: always

networks:
  weblab820:
    driver: bridge

volumes:
  mysql_data_new:
    driver: local
